title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
name: Dive into Machine Learning.
description: A place to learn Machine Learning headfirst.
